name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cablemodemstatus:$(date +%s)
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASS: ${{secrets.DOCKER_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Docker push
        docker push $DOCKER_USER/cablemodem-status:$(date +%s)
